broomsticks = ['comet 260', 'nimbus 2000', 'firebolt', 'cleansweep 7'] 
print("Is broomstick == 'nimbus 2000'? I predict True.")  
print(broomsticks[1] == 'nimbus 2000')
print("\nIs broomstick == 'nimbus 2000'? I predict False.") 
print(broomsticks[1] == 'firebolt')
print("\nIs broomstick != 'firebolt'? I predict True.")
print(broomsticks[1] != 'firebolt')
print("\nIs broomstick != 'firebolt'? I predict False.") 
print(broomsticks[1] != 'nimbus 2000')
print("\nIs broomstick in the list? I predict True.")
print('firebolt' in broomsticks)
print("\nIs broomstick in the list? I predict False.") 
print('sidewinder' in broomsticks) 
print("\nIs broomstick not in the list? I predict True.")
print('sidewinder' not in broomsticks) 
print("\nIs broomstick not in the list? I predict False.")
print('firebolt' not in broomsticks) 