print("a hawk would be a good pet.") 
print("a eagle would be a good pet.") 
print("a falcon would be a good pet.")
print("any of these birds would make a great pet!")  
print("one thing about birds is that they can fly.") 
print("they have feathers.")
print("they can be trained to do tricks.")
print("birds are very interesting animals.")
print("birds have wings.")
print("birds can be found all over the world.")
print("birds can be very social animals.")
print("birds can be very intelligent.")
print("birds can be very beautiful.")
print("birds can be very fun to watch.")
print("birds can be very entertaining.") 